// auth section
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

// registering
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_REQUEST_ERROR = 'USER_REGISTER_REQUEST_ERROR';

// fetching User info
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

// list actions
export const ADD_LIST = 'ADD_LIST';
export const ADD_TODO = 'ADD_TODO';

export const GET_ALL_LISTS = 'GET_ALL_LISTS';
export const GET_ALL_LISTS_ERROR = 'GET_ALL_LISTS_ERROR';

export const GET_USER_LISTS = 'GET_USER_LISTS';
export const GET_USER_LISTS_ERROR = 'GET_USER_LISTS_ERROR';
export const CREATE_USER_LIST = 'CREATE_USER_LIST';
export const CREATE_USER_LIST_ERROR = 'CREATE_USER_LIST_ERROR';

export const CREATE_USER_TODO = 'CREATE_USER_TODO';
export const CREATE_USER_TODO_ERROR = 'CREATE_USER_TODO_ERROR';

export const DELETE_USER_LIST_BY_ID_ERROR = 'DELETE_USER_LIST_BY_ID_ERROR';
export const UPDATE_ITEM_BY_ID_ERROR = 'UPDATE_ITEM_BY_ID_ERROR';

